set(CTEST_PROJECT_NAME "KWWidgets")
set(CTEST_NIGHTLY_START_TIME "21:30:00 EDT")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "public.kitware.com")
set(CTEST_DROP_LOCATION "/cgi-bin/HTTPUploadDartFile.cgi")
set(CTEST_TRIGGER_SITE "http://${CTEST_DROP_SITE}/cgi-bin/Submit-KWWidgets-TestingResults.cgi")
