KWConvertImageToHeader --zlib --base64 vtkKWWindowLayoutResources.h \
    KWWindowLayout1x1.png \
    KWWindowLayout1x2.png \
    KWWindowLayout2x1.png \
    KWWindowLayout2x2.png \
    KWWindowLayout2x3.png \
    KWWindowLayout3x2.png \
    KWWindowLayout3x3.png 

KWConvertImageToHeader --zlib --base64 vtkKWIconResources.h \
    angle_tool.png \
    bidimensional_tool.png \
    bounding_box.png \
    browserback.png \
    browserforward.png \
    browserup.png \
    bug_mini.png \
    calculator.png \
    camera.png \
    camera_mini.png \
    cdrom.png \
    color_bar_annotation.png \
    color_squares.png \
    color_alpha_squares.png \
    columns.png \
    compress.png \
    connection.png \
    contour_segment.png \
    contour_tool.png \
    contrast.png \
    corner_annotation.png \
    crop_tool.png \
    distance_tool.png \
    document.png \
    document_rgb_color.png \
    document_volume_property.png \
    document_window_level.png \
    edit_contrast.png \
    edit_volume_properties.png \
    empty_16x16.png \
    empty_1x1.png \
    error.png \
    error_mini.png \
    error_red_mini.png \
    expand.png \
    expand_left_mini.png \
    expand_mini.png \
    expand_right_mini.png \
    expand_up_mini.png \
    eye.png \
    favorites.png \
    file_open.png \
    filedelete.png \
    floppy.png \
    floppydrive.png \
    folder.png \
    folder32.png \
    folder_open.png \
    foldernew.png \
    folderxp.png \
    grayscale_squares.png \
    grid_linear.png \
    grid_log.png \
    harddisk.png \
    header_annotation.png \
    helpbubble.png \
    hsv_diagram.png \
    info_mini.png \
    interpolation_bilinear.png \
    interpolation_nearest.png \
    lock.png \
    mag_glass.png \
    minus.png \
    small_counter_blue_1.png \
    small_counter_blue_2.png \
    small_counter_blue_3.png \
    small_counter_blue_4.png \
    small_counter_blue_5.png \
    small_counter_blue_6.png \
    small_counter_blue_7.png \
    small_counter_blue_8.png \
    small_counter_blue_9.png \
    small_counter_blue_9plus.png \
    move.png \
    move_h.png \
    move_v.png \
    netdrive.png \
    oblique_probe.png \
    orientation_cube_annotation.png \
    pan_hand.png \
    parallel_projection.png \
    perspective_projection.png \
    plus.png \
    point_finger.png \
    preset_add.png \
    preset_apply.png \
    preset_delete.png \
    preset_email.png \
    preset_load.png \
    preset_locate.png \
    preset_next.png \
    preset_previous.png \
    preset_rewind.png \
    preset_update.png \
    preset_filter.png \
    question.png \
    reload.png \
    reset_camera.png \
    reset_contrast.png \
    rotate.png \
    rows.png \
    scale_bar_annotation.png \
    seed_tool.png \
    shrink.png \
    side_annotation.png \
    spin_down.png \
    spin_left.png \
    spin_right.png \
    spin_up.png \
    standard_view.png \
    stopwatch.png \
    testtube.png \
    time.png \
    transport_beginning.png \
    transport_end.png \
    transport_fast_forward.png \
    transport_fast_forward_to_key.png \
    transport_loop.png \
    transport_pause.png \
    transport_play.png \
    transport_play_backward.png \
    transport_play_to_key.png \
    transport_rewind.png \
    transport_rewind_to_key.png \
    transport_stop.png \
    trashcan.png \
    tree_close.png \
    tree_open.png \
    warning.png \
    warning_mini.png \
    window_level.png

KWConvertImageToHeader --zlib --base64 --use_path_in_name vtkKWNuvolaIconResources.h \
    Nuvola/16x16/actions/colorpicker.png \
    Nuvola/16x16/actions/configure.png \
    Nuvola/16x16/actions/decrypted.png \
    Nuvola/16x16/actions/editcopy.png \
    Nuvola/16x16/actions/editcut.png \
    Nuvola/16x16/actions/editpaste.png \
    Nuvola/16x16/actions/encrypted.png \
    Nuvola/16x16/actions/exit.png \
    Nuvola/16x16/actions/fileclose.png \
    Nuvola/16x16/actions/fileopen.png \
    Nuvola/16x16/actions/fileprint.png \
    Nuvola/16x16/actions/filesave.png \
    Nuvola/16x16/actions/help.png \
    Nuvola/16x16/actions/history.png \
    Nuvola/16x16/actions/kalarm.png \
    Nuvola/16x16/actions/ledblue.png \
    Nuvola/16x16/actions/ledgreen.png \
    Nuvola/16x16/actions/ledlightblue.png \
    Nuvola/16x16/actions/ledlightgreen.png \
    Nuvola/16x16/actions/ledorange.png \
    Nuvola/16x16/actions/ledpurple.png \
    Nuvola/16x16/actions/ledred.png \
    Nuvola/16x16/actions/ledyellow.png \
    Nuvola/16x16/actions/mail_generic.png \
    Nuvola/16x16/actions/message.png \
    Nuvola/16x16/actions/messagebox_critical.png \
    Nuvola/16x16/actions/messagebox_info.png \
    Nuvola/16x16/actions/messagebox_warning.png \
    Nuvola/16x16/actions/no.png \
    Nuvola/16x16/actions/rotate.png \
    Nuvola/16x16/actions/stop.png \
    Nuvola/16x16/actions/thumbnail.png \
    Nuvola/16x16/actions/view_bottom.png \
    Nuvola/16x16/actions/view_fullscreen.png \
    Nuvola/16x16/actions/view_left_right.png \
    Nuvola/16x16/actions/view_right.png \
    Nuvola/16x16/actions/view_top_bottom.png \
    Nuvola/16x16/actions/viewmag.png \
    Nuvola/16x16/actions/window_new.png \
    Nuvola/16x16/apps/ark.png \
    Nuvola/16x16/apps/bug.png \
    Nuvola/16x16/apps/email.png \
    Nuvola/16x16/apps/error.png \
    Nuvola/16x16/apps/keyboard.png \
    Nuvola/16x16/apps/ktimer.png \
    Nuvola/16x16/devices/camera.png \
    Nuvola/16x16/filesystems/folder_inbox.png \
    Nuvola/16x16/filesystems/folder_outbox.png \
    Nuvola/16x16/filesystems/trashcan_empty.png \
    Nuvola/16x16/filesystems/trashcan_full.png \
    Nuvola/22x22/actions/help.png \
    Nuvola/22x22/actions/messagebox_info.png \
    Nuvola/22x22/actions/misc.png \
    Nuvola/22x22/actions/wizard.png \
    Nuvola/22x22/apps/designer.png \
    Nuvola/22x22/filesystems/folder_blue.png \
    Nuvola/22x22/devices/camera.png \
    Nuvola/48x48/actions/messagebox_critical.png \
    Nuvola/48x48/actions/messagebox_info.png \
    Nuvola/48x48/actions/messagebox_warning.png \
    Nuvola/48x48/actions/help.png \
    Nuvola/48x48/actions/history.png \
    Nuvola/48x48/apps/download_manager.png \
    Nuvola/48x48/devices/mouse.png \
    Nuvola/48x48/filesystems/folder_blue.png

KWConvertImageToHeader --zlib --base64 --use_path_in_name vtkKWCrystalProjectIconResources.h \
    CrystalProject/16x16/actions/14_layer_deletelayer.png \
    CrystalProject/16x16/actions/14_layer_novisible.png \
    CrystalProject/16x16/actions/14_layer_visible.png \
    CrystalProject/16x16/actions/jabber_online.png \
    CrystalProject/16x16/actions/rotate.png \
    CrystalProject/16x16/apps/cookie.png \
    CrystalProject/16x16/apps/tutorials.png

KWConvertImageToHeader --zlib --base64 --use_path_in_name vtkKWSilkIconResources.h \
    Silk/accept.png \
    Silk/add.png \
    Silk/application_xp_terminal.png \
    Silk/arrow_refresh.png \
    Silk/attach.png \
    Silk/bin_closed.png \
    Silk/bug.png \
    Silk/bullet_toggle_minus.png \
    Silk/bullet_toggle_plus.png \
    Silk/camera.png \
    Silk/cancel.png \
    Silk/chart_curve.png \
    Silk/chart_line.png \
    Silk/chart_organisation.png \
    Silk/chart_pie.png \
    Silk/clock.png \
    Silk/cog.png \
    Silk/color_swatch.png \
    Silk/color_wheel.png \
    Silk/compress.png \
    Silk/cross.png \
    Silk/cut.png \
    Silk/date.png \
    Silk/delete.png \
    Silk/disk.png \
    Silk/door_in.png \
    Silk/door_out.png \
    Silk/email.png \
    Silk/exclamation.png \
    Silk/eye.png \
    Silk/film.png \
    Silk/help.png \
    Silk/hourglass.png \
    Silk/information.png \
    Silk/key.png \
    Silk/link.png \
    Silk/lock.png \
    Silk/magnifier.png \
    Silk/paintbrush.png \
    Silk/paintcan.png \
    Silk/paste_plain.png \
    Silk/pill.png \
    Silk/plugin.png \
    Silk/star.png \
    Silk/stop.png \
    Silk/telephone.png \
    Silk/text_allcaps.png \
    Silk/text_bold.png \
    Silk/text_italic.png \
    Silk/text_underline.png \
    Silk/thumb_down.png \
    Silk/thumb_up.png \
    Silk/tick.png \
    Silk/time.png \
    Silk/wrench.png \
    Silk/zoom.png \
    Silk/zoom_in.png \
    Silk/zoom_out.png

KWConvertImageToHeader --zlib --base64 vtkKWMiscResources.h \
    ErrorLogMenuEntry.png
