KWConvertImageToHeader --zlib --base64 vtkKWWindowLayoutResources.h \
    KWWindowLayout1x1.png \
    KWWindowLayout1x2.png \
    KWWindowLayout2x1.png \
    KWWindowLayout2x2.png \
    KWWindowLayout2x3.png \
    KWWindowLayout3x2.png \
    KWWindowLayout3x3.png 

KWConvertImageToHeader --zlib --base64 vtkKWIconResources.h \
    angle_tool.png \
    bidimensional_tool.png \
    bounding_box.png \
    browserback.png \
    browserforward.png \
    browserup.png \
    bug_mini.png \
    calculator.png \
    camera.png \
    camera_mini.png \
    cdrom.png \
    color_bar_annotation.png \
    color_squares.png \
    color_alpha_squares.png \
    columns.png \
    compress.png \
    connection.png \
    contour_segment.png \
    contour_tool.png \
    contrast.png \
    corner_annotation.png \
    crop_tool.png \
    distance_tool.png \
    document.png \
    document_rgb_color.png \
    document_volume_property.png \
    document_window_level.png \
    edit_contrast.png \
    edit_volume_properties.png \
    empty_16x16.png \
    empty_1x1.png \
    error.png \
    error_mini.png \
    error_red_mini.png \
    expand.png \
    expand_left_mini.png \
    expand_mini.png \
    expand_right_mini.png \
    expand_up_mini.png \
    eye.png \
    favorites.png \
    file_open.png \
    filedelete.png \
    floppy.png \
    floppydrive.png \
    folder.png \
    folder32.png \
    folder_open.png \
    foldernew.png \
    folderxp.png \
    grayscale_squares.png \
    grid_linear.png \
    grid_log.png \
    harddisk.png \
    header_annotation.png \
    helpbubble.png \
    hsv_diagram.png \
    info_mini.png \
    interpolation_bilinear.png \
    interpolation_nearest.png \
    lock.png \
    mag_glass.png \
    minus.png \
    move.png \
    move_h.png \
    move_v.png \
    netdrive.png \
    oblique_probe.png \
    orientation_cube_annotation.png \
    pan_hand.png \
    parallel_projection.png \
    perspective_projection.png \
    plus.png \
    point_finger.png \
    preset_add.png \
    preset_apply.png \
    preset_delete.png \
    preset_email.png \
    preset_load.png \
    preset_locate.png \
    preset_next.png \
    preset_previous.png \
    preset_update.png \
    question.png \
    reload.png \
    reset_camera.png \
    reset_contrast.png \
    rotate.png \
    rows.png \
    scale_bar_annotation.png \
    seed_tool.png \
    shrink.png \
    side_annotation.png \
    spin_down.png \
    spin_left.png \
    spin_right.png \
    spin_up.png \
    standard_view.png \
    stopwatch.png \
    testtube.png \
    time.png \
    transport_beginning.png \
    transport_end.png \
    transport_fast_forward.png \
    transport_fast_forward_to_key.png \
    transport_loop.png \
    transport_pause.png \
    transport_play.png \
    transport_play_backward.png \
    transport_play_to_key.png \
    transport_rewind.png \
    transport_rewind_to_key.png \
    transport_stop.png \
    trashcan.png \
    tree_close.png \
    tree_open.png \
    warning.png \
    warning_mini.png \
    window_level.png

KWConvertImageToHeader --zlib --base64 --use_path_in_name vtkKWNuvolaIconResources.h \
    Nuvola/16x16/actions/configure.png \
    Nuvola/16x16/actions/decrypted.png \
    Nuvola/16x16/actions/encrypted.png \
    Nuvola/16x16/actions/exit.png \
    Nuvola/16x16/actions/fileclose.png \
    Nuvola/16x16/actions/fileopen.png \
    Nuvola/16x16/actions/fileprint.png \
    Nuvola/16x16/actions/filesave.png \
    Nuvola/16x16/actions/help.png \
    Nuvola/16x16/actions/mail_generic.png \
    Nuvola/16x16/actions/message.png \
    Nuvola/16x16/actions/messagebox_critical.png \
    Nuvola/16x16/actions/messagebox_info.png \
    Nuvola/16x16/actions/messagebox_warning.png \
    Nuvola/16x16/actions/no.png \
    Nuvola/16x16/actions/rotate.png \
    Nuvola/16x16/actions/stop.png \
    Nuvola/16x16/actions/thumbnail.png \
    Nuvola/16x16/actions/viewmag.png \
    Nuvola/16x16/actions/view_bottom.png \
    Nuvola/16x16/actions/view_fullscreen.png \
    Nuvola/16x16/actions/view_right.png \
    Nuvola/16x16/apps/ark.png \
    Nuvola/16x16/apps/bug.png \
    Nuvola/16x16/apps/email.png \
    Nuvola/16x16/apps/error.png \
    Nuvola/16x16/apps/keyboard.png \
    Nuvola/16x16/devices/camera.png \
    Nuvola/16x16/filesystems/trashcan_empty.png \
    Nuvola/16x16/filesystems/trashcan_full.png \
    Nuvola/22x22/actions/help.png \
    Nuvola/22x22/actions/messagebox_info.png \
    Nuvola/22x22/actions/misc.png \
    Nuvola/22x22/apps/designer.png \
    Nuvola/22x22/filesystems/folder_blue.png \
    Nuvola/22x22/devices/camera.png \
    Nuvola/48x48/actions/messagebox_critical.png \
    Nuvola/48x48/actions/messagebox_info.png \
    Nuvola/48x48/actions/messagebox_warning.png \
    Nuvola/48x48/actions/history.png \
    Nuvola/48x48/apps/download_manager.png \
    Nuvola/48x48/devices/mouse.png \
    Nuvola/48x48/filesystems/folder_blue.png

KWConvertImageToHeader --zlib --base64 --use_path_in_name vtkKWCrystalProjectIconResources.h \
    CrystalProject/16x16/actions/14_layer_deletelayer.png \
    CrystalProject/16x16/actions/14_layer_novisible.png \
    CrystalProject/16x16/actions/14_layer_visible.png \
    CrystalProject/16x16/actions/jabber_online.png \
    CrystalProject/16x16/actions/rotate.png \
    CrystalProject/16x16/apps/cookie.png

KWConvertImageToHeader --zlib --base64 vtkKWMiscResources.h \
    ErrorLogMenuEntry.png
